### PR TITLE
html : coding up the designs

### PR DESCRIPTION
**Pull request by thelostone-mc**
### Description 
- Coded up the UI as per the sketch designs provided by @PixelantDesign 
- file structure altered
- added new npm packages
- partially optimized for smaller devices

### CODE REVIEW

**Comment by thelostone-mc** [comment]
@eswarasai could you check it out (I've got it optimized for smaller devices too except a few hiccups)

screenshot-2018-2-21 home coldoutreach


screenshot-2018-2-21 home coldoutreach 1


screenshot-2018-2-21 home coldoutreach 2



cc: @PixelantDesign  @owocki

**Comment by thelostone-mc** [comment]
Forgot to the add the blue cane design ^_^


screenshot-2018-2-24 home coldoutreach

**Comment by PixelantDesign** [comment]
Looks great! 

Could we add collapse and expand on the email formatting? 

Or maybe its best to decrease/limit the number of options to format. One thing we want to avoid us allowing senders to make the email look circusy, it could detract from the seriousness of the outreach email.

Thoughts?

**Comment by PixelantDesign** [comment]
I have to say, you guys are amazing @thelostone-mc @eswarasai!

**Comment by eswarasai** [comment]
@PixelantDesign -- All credits goes to @thelostone-mc. Amazing work 👍 

@thelostone-mc -- If you don't mind, can you rebase your branch with `coldoutreach:master` and push the changes? Let me know if you need any help with this.

**Comment by thelostone-mc** [comment]
@PixelantDesign We can reduce the number of options on the editor. That's a a few lines of code ^_^
I'll get it done once everything else is set 

@eswarasai not cool !! you just give me loads of conflicts to resolve. This shall not be forgotten :P
I'll update the PR but hold off pushing code for an hour :P

**Comment by eswarasai** [comment]
@PixelantDesign @thelostone-mc -- Is this good to merge?
BTW, no need to worry too much about the Text Editor right away as this is going to be MVP. Confirmed this with @owocki too.

**Comment by thelostone-mc** [comment]
@eswarasai yup!

**Comment by owocki** [comment]
😍 these designs look so good

**Comment by owocki** [comment]
im excited to see this making progress :)  let me know what i can do to help

**Pull request merged**
